### ISSUE TITLE
Translate extensions and emulators app inventor 

### ISSUE THREAD

**Issue by aliaia744046** [SusanRatiLane/appinventor-translations#4]
How is translation done Are there programs or websites Can you teach me I would like to translate into Arabic

**Comment by SusanRatiLane** [comment]
> How is translation done Are there programs or websites Can you teach me I would like to translate into Arabic

We would be delighted to have your help in translating. An Arabic translation has begun multiple times but never completed. 

To become a translator, create an account at http://weblate.appinventor.mit.edu and then contact me so that I can grant access. 

Here is a video tutorial on how our weblate translation system works: https://www.youtube.com/watch?v=VFwTn32MrBw

**Comment by aliaia744046** [comment]
Thank you, I'll have fun with it because the holidays are about to start.

في الأربعاء، ٧ يوليو ٢٠٢١ ٥:١٩ م Susan Rati Lane ***@***.***>
كتب:

**Comment by aliaia744046** [comment]
I cannot retrieve the information. I think you mentioned to me that you
should give permission for that

في الأربعاء، ٧ يوليو ٢٠٢١ ٨:٠٥ م علي مكي نعمه لخدمات FTTX <
***@***.***> كتب:

**Comment by SusanRatiLane** [comment]
Resolved outside of Github
